spring.application.name=retail_management_system
# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/retail_management_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true

# Logging
logging.level.com.retail=DEBUG
logging.level.org.springframework.web=INFO

# CORS Configuration (for React frontend)
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
cors.allowed-methods=${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
cors.allowed-headers=${CORS_ALLOWED_HEADERS:*}
cors.allow-credentials=${CORS_ALLOW_CREDENTIALS:true}
cors.max-age=${CORS_ALLOWED_ORIGINS:3600}

#endpoints
security.public-endpoints=/api/auth/**,/api/products/**,/api/cart/**,/api/orders/**
security.wholesaler-endpoints=/api/wholesaler/**
security.seller-endpoints=/api/cart/**,/api/orders/**
secutyry.salesman-endpoints=/api/salesman/**

#JWT configuration
jwt.secret=${JWT_SECRET:mysecretkeytocreatejwttokes123434567800}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.header-name=${JWT_HEADER_NAME:Authorization}
jwt.token-prefix=${JWT_TOKEN_PREFIX:Bearer}