// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/wholesaler": {
    params: {};
  };
  "/wholesaler/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/wholesaler" | "/wholesaler/products";
  };
  "routes/auth/layout.tsx": {
    id: "routes/auth/layout";
    page: "/auth/login" | "/auth/register";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/auth/register";
  };
  "routes/wholesaler.tsx": {
    id: "routes/wholesaler";
    page: "/wholesaler" | "/wholesaler/products";
  };
  "routes/wholesaler/dashboard.tsx": {
    id: "routes/wholesaler/dashboard";
    page: "/wholesaler";
  };
  "routes/wholesaler/products.tsx": {
    id: "routes/wholesaler/products";
    page: "/wholesaler/products";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/layout": typeof import("./app/routes/auth/layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/wholesaler": typeof import("./app/routes/wholesaler.tsx");
  "routes/wholesaler/dashboard": typeof import("./app/routes/wholesaler/dashboard.tsx");
  "routes/wholesaler/products": typeof import("./app/routes/wholesaler/products.tsx");
};